FROM openjdk:8-jre-alpine as builder

ARG BUKKIT_VERSION=1.15.1
LABEL stage=builder
LABEL build=$BUILD_ID

LABEL maintainer="SpartanerSpaten <espriworkemail@gmail.com>" \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.name="MC-Pillage" \
  org.label-schema.description="Get notified when important things happen" \
  org.label-schema.vcs-ref=$VCS_REF \
  org.label-schema.vendor="SpartanerSpaten / EinSpaten" \
  org.label-schema.version=$VERSION \
  org.label-schema.schema-version="v0.1a"



