name: mc-pillage
main: com.einspaten.bukkit.mcpillage.MCPillagePlugin
version: ${version}
api-version: 1.15
authors:
  - SpartanerSpaten (EinSpaten)
  - Use-To
website: https://github.com/SpartanerSpaten/MC-Pillage
commands:
  farm:
    description: Teleports Player into the given Farmworld Dimension or Creates a new requires Op rights
    usage: /farm <overworld, nether, end, create>
  shop:
    description: Lets player buy spawn eggs
    usage: /shop
  home:
    description: teleports player to his home
    usage: /home <set>
  city:
    description: Plot managment
    usage: /city <buy>
  money:
    description: Money Command
    usage: /money <pay>
  plot:
    description: Command for plot things
    usage: /plot [buy, add, remove, sell]