name: mc-pillage
main: com.einspaten.bukkit.mcpillage.MCPillagePlugin
version: ${version}
api-version: 1.15
authors:
  - SpartanerSpaten (EinSpaten)
  - Use-To
website: https://github.com/SpartanerSpaten/MC-Pillage
commands:
  war:
    description: Base Command for starting stoping and inforamtion about wars.
    usage: /war <start, stop, info>
  faction:
    description: Base Commands for managing factions
    usage: /factions <add, kick, promote, forceleader, forceadd>
  farm:
    description: Teleports Player into the given Farmworld Dimension or Creates a new requires Op rights
    usage: /farm <overworld, nether, end, create>
  eggshop:
    description: Lets player buy spawn eggs
    usage: /shop
